# Generated by Django 5.1.5 on 2025-02-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('nombre_padre', models.CharField(max_length=255)),
                ('nombre_madre', models.CharField(max_length=255)),
                ('grado', models.CharField(max_length=50)),
                ('seccion', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
    ]
